[versions]
agp = "8.13.2"
kotlin = "2.2.21"
jsoup = "1.21.2"

[libraries]
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
